WITH SALES AS(
SELECT FISCALPERIOD, FISCALYEAR, SUM(QTYSHIP) AS QTY_SOLD
FROM InvoiceDetailHistory
GROUP BY fiscalPeriod, fiscalYear )

SELECT fiscalPeriod, fiscalYear, QTY_SOLD,
	AVG(QTY_SOLD) OVER(ORDER BY FISCALYEAR ASC, FISCALPERIOD ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MOVING_AVG_QTY
FROM SALES;

WITH SALES AS(
SELECT FISCALPERIOD, FISCALYEAR, SUM(QTYSHIP) AS QTY_SOLD
FROM InvoiceDetailHistory
GROUP BY fiscalPeriod, fiscalYear )

SELECT fiscalPeriod, fiscalYear, QTY_SOLD,
	SUM(QTY_SOLD) OVER(ORDER BY FISCALYEAR ASC, FISCALPERIOD ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MOVING_TOTAL_QTY
FROM SALES
