WITH SALES AS(
SELECT ITEM, FISCALPERIOD, FISCALYEAR, SUM(QTYSHIP) AS QTY_SOLD
FROM InvoiceDetailHistory 
WHERE SUPERGRP = '6'
GROUP BY ITEM, fiscalPeriod, fiscalYear )

SELECT ITEM, fiscalPeriod, fiscalYear, QTY_SOLD,
	AVG(QTY_SOLD) OVER(ORDER BY ITEM ASC, FISCALYEAR ASC, FISCALPERIOD ASC ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS SIX_MO_AVG_QTY,
	AVG(QTY_SOLD) OVER(ORDER BY ITEM ASC, FISCALYEAR ASC, FISCALPERIOD ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS THREE_MO_AVG_QTY
FROM SALES S
JOIN DCSCIM C ON C.ITMID = S.ITEM
WHERE S.FISCALYEAR > '2025'
AND COPCLSCD = 'RSLE' ;

WITH SALES AS(
SELECT FISCALPERIOD, FISCALYEAR, SUM(QTYSHIP) AS QTY_SOLD
FROM InvoiceDetailHistory
GROUP BY fiscalPeriod, fiscalYear )

SELECT fiscalPeriod, fiscalYear, QTY_SOLD,
	SUM(QTY_SOLD) OVER(ORDER BY FISCALYEAR ASC, FISCALPERIOD ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MOVING_TOTAL_QTY
FROM SALES
