-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
----- AGGREGATING INVENTORY BY WAREHOUSE -----
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

----- BEGIN WEIGHTED AVG QTY SOLD (6-MONTH) CALCULATION -----

-- Total business days (6-months)
WITH DAY_COUNT_TOTAL AS (
    SELECT COUNT(*) AS TOTAL_DAYS
    FROM DimDate
    WHERE calendardate >= DATEADD(MONTH, -7, GETDATE())
      AND calendardate < DATEADD(MONTH, -1, GETDATE())
      AND businessDay = 'Y'
),

-- 6-month Moving Qty Sold
SIX_MO_INVOICE AS (
    SELECT I.ORDERWAREHOUSE AS PLT, ITEM, SUM(QTYSHIP) AS QTYSOLD
    FROM InvoiceDetailHistory I
    INNER JOIN DimDate DT ON DT.CALENDARDATE = I.invoiceDate
    WHERE calendardate >= DATEADD(MONTH, -7, GETDATE())
      AND calendardate < DATEADD(MONTH, -1, GETDATE())
	  AND orderType ='RG'
    GROUP BY I.ORDERWAREHOUSE, ITEM
),

-- 3-month Moving Qty Sold 
THREE_MO_INVOICE AS (
    SELECT I.ORDERWAREHOUSE AS PLT, ITEM, (SUM(QTYSHIP)*2) AS QTYSOLD
    FROM InvoiceDetailHistory I
    INNER JOIN DimDate DT ON DT.CALENDARDATE = I.invoiceDate
    WHERE calendardate >= DATEADD(MONTH, -4, GETDATE())
      AND calendardate < DATEADD(MONTH, -1, GETDATE())
	  AND orderType ='RG'
    GROUP BY I.ORDERWAREHOUSE, ITEM
),

-- Wighted average of Sales Qty (6-months)
TOTAL_INVOICES AS (
	SELECT S.PLT, S.ITEM, (T.QTYSOLD + S.QTYSOLD)/2 AS QTYSOLD
	FROM SIX_MO_INVOICE S
	JOIN THREE_MO_INVOICE T ON S.ITEM = T.ITEM AND S.PLT = T.PLT
),


-- Join DCSDIM with Qty Weighted Avg
WEIGHTED_AVG AS (
    SELECT 
        D.PLT, D.ITMID, C.ITMDESC, C.PRDGRP, C.VNDID,
		D.SYSAVGCST AS AVG_COST, C.ITMST,
		D.OHQTY, D.POONORDQTY, D.OUTSTKQTY AS BACKORDR, 
		SUM(OHQTY - (OUTSTKQTY + COPSALCQTY)) AS ITMSTS,
        ISNULL(CAST(S.QTYSOLD AS DECIMAL (18,4)), 0) AS QTY_SOLD 
    FROM DCSDIM D
	LEFT JOIN TOTAL_INVOICES S
		ON D.ITMID = S.ITEM AND D.PLT = S.PLT
	LEFT JOIN DCSCIM C
		ON C.ITMID = D.ITMID
	WHERE C.COPCLSCD = 'RSLE'
	GROUP BY D.PLT, D.ITMID, C.ITMDESC, C.PRDGRP, C.VNDID, C.ITMST,
		D.SYSAVGCST, D.OHQTY, D.POONORDQTY, D.OUTSTKQTY, S.QTYSOLD
),
  
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
----- BEGIN LEAD TIME CALCULATION -----
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  
-- PO Order Issue Date --
ISSUE_DATE AS(
SELECT PLT, ITMID, PONBR, ISSDTE, calendarDate AS ISSDATE
FROM DPMORDM3 M3
INNER JOIN DIMDATE D ON M3.ISSDTE = D.julianDate
),

-- PO Order Recipt Date (24-Month Filter) --
RECPT_DATE AS(
SELECT PLT, ITMID, PONBR, LSTRECPDTE, calendarDate AS RECPDATE
FROM DPMORDM3 M3
INNER JOIN DIMDATE D ON M3.LSTRECPDTE = D.mdyDate
WHERE calendardate >= DATEADD(MONTH, -24, GETDATE())
), 

-- System Lead Time --
EOQ AS(
SELECT PLT, ITMID, EXTLEDTIM, INTLEDTIM
FROM EOQCALP
),

-- Inner Join ISSUE & RECIPT / Left Join EOQ --
DATE_DIFF AS(
SELECT 
	RD.PLT, RD.ITMID, RD.PONBR, ID.ISSDATE, RD.RECPDATE,
	SUM(E.EXTLEDTIM + E.INTLEDTIM) AS SYSLEDTIME, DATEDIFF(DAY, ISSDATE, RECPDATE) AS LEAD_TIME
FROM ISSUE_DATE ID
INNER JOIN RECPT_DATE RD ON ID.PONBR = RD.PONBR AND ID.PLT = RD.PLT AND ID.ITMID = RD.ITMID
LEFT JOIN EOQ E ON E.PLT = ID.PLT AND E.ITMID = ID.ITMID
GROUP BY RD.PLT, RD.ITMID, RD.PONBR, ID.ISSDATE, RD.RECPDATE, ISSDATE, RECPDATE
),

-- Calculate Average Lead Time (Group by ITEM & PLT) --
AVG_LEADTIME AS(
  SELECT D.PLT, D.ITMID, SYSLEDTIME,
    CASE 
      WHEN AVG(CAST(LEAD_TIME AS DECIMAL(10,2))) > 300 THEN 300 
      ELSE AVG(CAST(LEAD_TIME AS DECIMAL(10,2))) 
    END AS AVG_LT
  FROM DATE_DIFF D
  GROUP BY D.PLT, D.ITMID, SYSLEDTIME
),

-- Convert Lead Time from Calendar Days to Business Days --
LT_FINAL AS(
SELECT D.PLT, D.ITMID, D.AVG_LT, ((D.AVG_LT*5)/7) as AVG_LT_BD, ISNULL(D.SYSLEDTIME, 0) AS SYSLEDTIME
FROM AVG_LEADTIME D
),
  
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
----- Left Join WEIGHTED AVG QTY & LEAD TIME -----
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- Calculate Total Supply Chain (TSC) / Avg Demand / Demand Cost --
ALL_JOINED AS(
SELECT 
	D.PLT, D.ITMID, D.ITMDESC, D.ITMST, 
	D.PRDGRP, D.VNDID, D.AVG_COST, 
	D.OHQTY, D.POONORDQTY, D.BACKORDR, 
	D.ITMSTS, D.QTY_SOLD, 
	(ITMSTS + POONORDQTY) AS TSC,
	ISNULL(L.SYSLEDTIME, 0) AS SYS_LT,
	ISNULL(ABS(CAST(L.AVG_LT_BD AS DECIMAL(10,2))), 0) AS AVG_LT_BD, 
	CASE 
		WHEN D.QTY_SOLD / DT.TOTAL_DAYS < 0 
		THEN 0 ELSE CAST((D.QTY_SOLD / DT.TOTAL_DAYS) AS DECIMAL(18,2)) END AS AVG_DAILY_DMD,
	CASE
		WHEN (D.QTY_SOLD / DT.TOTAL_DAYS) * AVG_COST < 0
		THEN 0 ELSE CAST((D.QTY_SOLD / DT.TOTAL_DAYS) * AVG_COST AS DECIMAL (18,2)) END AS DMD_COST
FROM WEIGHTED_AVG D
LEFT JOIN LT_FINAL L
	ON L.PLT = D.PLT AND L.ITMID = D.ITMID
CROSS JOIN DAY_COUNT_TOTAL DT

),

-- Calculate Inventory LT Difference / Days-On-Hand / On-Hand Value / Days-On-Order
DAYS_ON AS(
SELECT *, 
	CAST((AVG_LT_BD - SYS_LT) AS DECIMAL (10,2)) AS LT_DAY_DIFF,
	CASE 
		WHEN AVG_LT_BD = 0 THEN 0
		WHEN SYS_LT = 0 THEN 0
		ELSE (AVG_LT_BD - SYS_LT) / (AVG_LT_BD + SYS_LT) END AS LT_DIFF_PER,
	CASE 
		WHEN AVG_DAILY_DMD = 0 AND ITMSTS <= 0 THEN 0
		WHEN AVG_DAILY_DMD = 0 AND ITMSTS > 0 THEN 365
		WHEN ITMSTS / AVG_DAILY_DMD > 365 THEN 365
		WHEN ITMSTS / AVG_DAILY_DMD < 0 THEN 0
		ELSE CAST(ITMSTS / AVG_DAILY_DMD AS DECIMAL (18,2)) END AS DOH,
	ABS(ITMSTS * AVG_COST) AS DOH_VALUE,
	CASE
		WHEN AVG_DAILY_DMD = 0 AND POONORDQTY <= 0 THEN 0
		WHEN AVG_DAILY_DMD = 0 AND POONORDQTY > 0 THEN 365
		WHEN POONORDQTY / AVG_DAILY_DMD > 365 THEN 365
		WHEN POONORDQTY / AVG_DAILY_DMD < 0 THEN 0
		ELSE CAST(POONORDQTY / AVG_DAILY_DMD AS DECIMAL (18,2)) END AS DOO
FROM ALL_JOINED
),

-- Calculate Inventory Total Supply Chain Adjusted / Days-On-Hand Adjusted / Days-On-Order Adjusted
DAYS_ADJ AS( 
SELECT *, 
	CASE 
		WHEN DOH < 30  THEN TSC
		ELSE (TSC + (TSC*LT_DIFF_PER)) END AS ADJ_TSC,
	CASE 
		WHEN DOH < 30 THEN DOH
		ELSE (DOH + (DOH*LT_DIFF_PER)) END AS ADJ_DOH,
	CASE
		WHEN DOH < 30 THEN DOO
		ELSE (DOO + (DOO*LT_DIFF_PER)) END AS ADJ_DOO
	FROM DAYS_ON
)

-- Calculate Final Cost Savings with New Lead Time --
SELECT *, 
	(TSC - ADJ_TSC) * AVG_COST AS TSC_COST_DIFF
FROM DAYS_ADJ
ORDER BY TSC_COST_DIFF DESC
