WITH RECPT_DTE AS(
SELECT 
	M3.PLT, 
	M3.ITMID, 
	PONBR, 
	calendarDate AS RECPTDATE
FROM DPMORDM3 M3
JOIN DCSCIM C ON M3.ITMID = C.ITMID
INNER JOIN DIMDATE D ON M3.LSTRECPDTE = D.mdyDate
WHERE C.COPCLSCD IN('RSLE','VLFG') 
AND calendarYear >= '2024' 
),

ISSUE_DATE AS(
SELECT 
	M3.PLT, 
	M3.ITMID, 
	PONBR, 
	calendarDate AS ISSDATE
FROM DPMORDM3 M3
JOIN DCSCIM C ON M3.ITMID = C.ITMID
INNER JOIN DIMDATE D ON M3.ISSDTE = D.julianDate
WHERE C.COPCLSCD IN('RSLE','VLFG')
AND calendarYear >= '2023' 
),

DATE_DIFFS AS(
SELECT 
	I.PLT, 
	I.ITMID, 
	I.PONBR, 
	CAST(I.ISSDATE AS DATE) AS ISSDATE, 
	CAST(R.RECPTDATE AS DATE) AS RECPTDATE,
	CASE 
		WHEN AVG(DATEDIFF(DAY, ISSDATE, RECPTDATE)) > 600 THEN 600
		ELSE AVG(DATEDIFF(DAY, ISSDATE, RECPTDATE)) END AS LEAD_TIME
FROM ISSUE_DATE I
JOIN RECPT_DTE R ON I.ITMID = R.ITMID AND I.PLT = R.PLT AND I.PONBR = R.PONBR
GROUP BY I.PLT, I.ITMID, I.PONBR, I.ISSDATE, R.RECPTDATE
),

DATE_DIFFS_BD AS(
SELECT 
	PLT, ITMID, PONBR, ISSDATE, RECPTDATE,
	CAST(LEAD_TIME AS DECIMAL (18,2)) AS LEAD_TIME
FROM DATE_DIFFS
),

FINAL_PO_TABLE AS(
SELECT *, 
	CASE 
		WHEN LEAD_TIME <=5 THEN LEAD_TIME
		ELSE CEILING(((LEAD_TIME*5)/7)) END AS LT_BD
FROM DATE_DIFFS_BD
WHERE ITMID <> 'CANCELLED' AND PLT <> 'MFG'
),

ISSUE_DATE_2 AS(
SELECT PLT, ITMID, PONBR, ISSDTE, calendarDate AS ISSDATE
FROM DPMORDM3 M3
INNER JOIN DIMDATE D ON M3.ISSDTE = D.julianDate
WHERE D.calendarYear >= '2023'
), -- ISSUE DATE --

RECPT_DATE_2 AS(
SELECT PLT, ITMID, PONBR, LSTRECPDTE, calendarDate AS RECPDATE
FROM DPMORDM3 M3
INNER JOIN DIMDATE D ON M3.LSTRECPDTE = D.mdyDate
WHERE D.calendarYear >= '2024'
), -- RECPT DATE --

EOQ AS(
SELECT PLT, ITMID, EXTLEDTIM, INTLEDTIM
FROM EOQCALP
),

DATE_DIFF_2 AS(
SELECT 
	RD.PLT, RD.ITMID, RD.PONBR, ID.ISSDATE, RD.RECPDATE, E.EXTLEDTIM, E.INTLEDTIM,
	(E.EXTLEDTIM + E.INTLEDTIM) AS SYSLEDTIME, DATEDIFF(DAY, ISSDATE, RECPDATE) AS LEAD_TIME
FROM ISSUE_DATE_2 ID
INNER JOIN RECPT_DATE_2 RD ON ID.PONBR = RD.PONBR AND ID.PLT = RD.PLT AND ID.ITMID = RD.ITMID
LEFT JOIN EOQ E ON E.PLT = ID.PLT AND E.ITMID = ID.ITMID
), -- JOIN & DATE DIFF CALC --

AVG_LEADTIME AS(
  SELECT PLT, ITMID, SYSLEDTIME, EXTLEDTIM, INTLEDTIM,
    CASE 
      WHEN AVG(CAST(LEAD_TIME AS DECIMAL(10,2))) > 365 THEN 365 
      ELSE AVG(CAST(LEAD_TIME AS DECIMAL(10,2))) 
    END AS AVG_LT
  FROM DATE_DIFF_2 D
  GROUP BY D.PLT, D.ITMID, SYSLEDTIME, EXTLEDTIM, INTLEDTIM
), -- AVG LEAD TIME CALC --

FINAL_AVG_LT_TABLE AS(
SELECT 
	CIM.VNDID, CIM.ITMDESC, CIM.PRDGRP, 
	D.PLT, D.ITMID, 
	ISNULL(D.EXTLEDTIM, 0) AS EXTLEDTIM, 
	ISNULL(D.INTLEDTIM, 0) AS INTLEDTIM,
	D.AVG_LT, 
	((D.AVG_LT*5)/7) as AVG_LT_BD, 
	ISNULL(D.SYSLEDTIME, 0) AS SYSLEDTIME,
	OHQTY-(OUTSTKQTY+COPSALCQTY) AS ITMSTS
FROM AVG_LEADTIME D
JOIN DCSCIM CIM ON CIM.ITMID = D.ITMID
JOIN DCSDIM DIM ON DIM.ITMID = D.ITMID AND DIM.PLT = D.PLT
WHERE CIM.COPCLSCD IN ('RSLE','VLFG') AND AVG_LT >= 0
)

SELECT 
	PO.PLT,
	VNDID,
	PO.ITMID,
	ITMDESC,
	PRDGRP,
	PONBR,
	ISSDATE,
	RECPTDATE,
	LEAD_TIME,
	LT_BD,
	MAX(LT_BD) OVER(PARTITION BY PO.ITMID, PO.PLT) AS MAX_LT,
	MIN(LT_BD) OVER(PARTITION BY PO.ITMID, PO.PLT) AS MIN_LT,
	DATEDIFF(DAY, LAG(ISSDATE) OVER(PARTITION BY PO.PLT, PO.ITMID ORDER BY ISSDATE ASC), ISSDATE) AS ORDR_FREQUENCY,
	EXTLEDTIM,
	INTLEDTIM,
	SYSLEDTIME,
	CEILING(AVG_LT) AS AVG_LT,
	CEILING(AVG_LT_BD) AS AVG_LT_BD,
	AVG(AVG_LT_BD) OVER(PARTITION BY ALT.VNDID, ALT.PLT) AS AVG_VND_LT,
	ITMSTS
FROM FINAL_PO_TABLE PO
INNER JOIN FINAL_AVG_LT_TABLE ALT
	ON PO.ITMID = ALT.ITMID AND PO.PLT = ALT.PLT
;
